server:
  port: 9090


#spring:
#  sql:
#    init:
#      mode: always # 매번 초기화 실행되도록 설정
#      encoding: utf-8
#  datasource:
#    hikari:
#      driver-class-name: org.h2.Driver
#      # MODE: 실제 사용될 DB 유형 설정
#      # h2:mem:{dbname}: In-memory 사용 / h2:~/{dbname}: local db 사용
#      jdbc-url: jdbc:h2:mem:test;DATABASE_TO_UPPER=false;
#      username: sa
#      password:
#  jpa:
#    open-in-view: false
#    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    defer-datasource-initialization: true # true: Hibernate 초기화 후 DML 스크립트가 실행된다.
#  h2:
#    console:
#      enabled: true
#      path: /h2-console